In [14]:
import numpy as np
a = np.array([1, 2, 3])
b = a.shape # tra ve tuple
print(b)
c = np.array([[1, 2, 3, 3], [4, 5, 6, 9]])
print(c[1, 2])
d = c.shape
print(d)

(3,)
6
(2, 4)


In [34]:
a = np.random.random((3))
print(a)
np.random.random((2, 2))

[0.80351665 0.11360172 0.27711721]


array([[0.64167809, 0.49273731],
       [0.50655608, 0.46144026]])

In [41]:
np.random.seed(12) #RANDOM MANG NGAU NHIEN NHUNG CAC PHAN TU KHONG DOI KHI CHAY LAI
a = np.random.random((3))
print(a)
np.random.random((2, 2))

[0.15416284 0.7400497  0.26331502]


array([[0.53373939, 0.01457496],
       [0.91874701, 0.90071485]])